# Generated by Django 3.2.4 on 2021-11-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderplaced_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('FR', 'Frozen and Chilled'), ('B', 'Bakery'), ('CA', 'Car Accessories'), ('RF', 'Restaurant Food'), ('GR', 'Groceries')], max_length=2),
        ),
    ]
