# Generated by Django 3.2.4 on 2021-11-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('EL', 'Electronics'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('FR', 'Frozen and Chilled'), ('B', 'Bakery'), ('CA', 'Car Accessories'), ('RF', 'Restaurant Food'), ('GR', 'Groceries'), ('BK', 'Bakeries'), ('RF', 'Restaurant Food')], max_length=2),
        ),
    ]
